### ISSUE TITLE
unique_together problem with MySQL

### ISSUE THREAD

**Issue by mdgart** [worldcompany/djangoembed#1]
I got this error when I tried syncdb:
_mysql_exceptions.OperationalError: (1170, "BLOB/TEXT column 'match' used in key specification without a key length")
To solve the problem i removed 'match' from the StoredOEmbed unique_together Meta.

**Comment by coleifer** [comment]
Looks like this bug has been floating around for a while:
http://code.djangoproject.com/ticket/2495

**Comment by coleifer** [comment]
fixed in http://github.com/worldcompany/djangoembed/commit/42262c11277904a3d470ab7ec15445f7a001db96

**Comment by mdgart** [comment]
Thanks!

**Comment by djm** [comment]
The fix broke Django pre version 1.2 compatibility, check these 2 commits for a quick fix; there is a pull request though.

2010-10-18 @ http://github.com/djm/djangoembed/commits/master
