### ISSUE TITLE
Try to import Image both ways

### ISSUE THREAD

**Issue by robhudson** [worldcompany/djangoembed#12]
I have PIL installed but the `import Image` is failing for me. Perhaps this should use something similar what Django did here: http://code.djangoproject.com/changeset/12429.  Apparently PIL can be installed in different but incompatible ways?

**Comment by robhudson** [comment]
Here's the URL with out the period in it:
http://code.djangoproject.com/changeset/12429

**Comment by coleifer** [comment]
fixed
