### ISSUE TITLE
Getting IntegrityError when trying to hit an endpoint for the first time

### ISSUE THREAD

**Issue by dryan** [worldcompany/djangoembed#17]
http://dpaste.com/537543/ is the traceback

**Comment by coleifer** [comment]
I'm not sure what that could be...are you able to run tests?

**Comment by dryan** [comment]
Tests are failing. It looks like I might have data corruption on my drive. I'll post back after I run some tests on that.

**Comment by dryan** [comment]
Gotten the drive back to normal.

Testing fails (and not just in oembed): https://gist.github.com/949947
This is on OS X 10.6 running MySQL 5.5 and on Ubuntu running MySQL 5.1.

The error occurs when a StoredOEmbed is created without a content_type set, even though that is set to allow null values. It appears to be caused by the Foreign Key constraint placed on the content_type field. (If I manually remove the constraint then everything works as expected.)

**Comment by coleifer** [comment]
Are you missing the django.contrib.sites app?
