### ISSUE TITLE
Syncdb doesn't load fixtures

### ISSUE THREAD

**Issue by mdgart** [worldcompany/djangoembed#2]
I'm using Django 1.1.2 with MySQL, how to manually load the providers?

EDIT: I used pip to install djangoembed from source (git+http://...), and for some reason it didn't download the fixtures dir, so this is solved.

**Comment by mdgart** [comment]
pip install git+http://github.com/worldcompany/djangoembed.git doesn't download the fixtures folder.

**Comment by coleifer** [comment]
Thanks for reporting this!

fixed in http://github.com/worldcompany/djangoembed/commit/9a6d0ea84aaeda930d34b4e6d533309af78ee8ad
