### ISSUE TITLE
adding a provider

### ISSUE THREAD

**Issue by domguard** [worldcompany/djangoembed#22]
perhaps I did not get everything but I tested Slideshare : working

I tried to modify the endpoint to use the official one, took the URL from [Slideshare site](http://www.slideshare.net/developers/oembed)

```
http://www.slideshare.net/api/oembed/2
```

But this doesn't work (the endpoint returns XML)
Is this app tied to embedly specific flow ?

**Comment by domguard** [comment]
is this app sponsored by embedly ? (just asking)
I not the provider fixttures could be updated because lots of these providers have their own oembed endpoint now

**Comment by coleifer** [comment]
Should be fixed now, you will need to reload the initial data fixture.

**Comment by domguard** [comment]
thanks 

Dailymotion has also its own endpoint but somehow I could not make it work with djangoembed:

http://www.dailymotion.com/doc/api/oembed.html

What is the better way to get a debug output so I can fix it myself ?

**Comment by coleifer** [comment]
I would suggest using `ipdb` or `pdb` to step through the code -- it looks like all you need is to set up a provider for http://www.dailymotion.com/services/oembed
