### ISSUE TITLE
Bring back the docs

### ISSUE THREAD

**Issue by richardcornish** [worldcompany/djangoembed#38]
Documentation seems to have vanished. 

http://charlesleifer.com/docs/djangoembed/

**Comment by coleifer** [comment]
Sorry, must've got lost while I ported my site from django -> flask the other week.  Official docs updated to readthedocs:

http://djangoembed.readthedocs.org/en/latest/index.html

Also, check out https://github.com/coleifer/micawber -- a replacement for djangoembed which i'll be maintaining

**Comment by richardcornish** [comment]
@coleifer Thanks for being quick to put them back up. I tried micawber but I think I still prefer djangoembed. I used Embedly's endpoints, which rendered tweets pretty well, but when used with other filters, mangled the output. Half the HTML was escaping and half was trying to be rendered. I know chaining filters can sometimes have unexpected results. I believe the cause was using micawber with the Typogrify filter, which usually plays nice with other filters.

**Comment by coleifer** [comment]
That's no good.  If you wouldn't mind, I'd really be grateful if you
could create an issue on the micawber project so I can address this.
In my testing I didn't run into issues, but I didn't try much
chaining.

If you don't mind including a sample of text and the filters you used,
I'll be quick to address this in micawber:
https://github.com/coleifer/micawber/issues

On Thu, Apr 26, 2012 at 4:47 PM, Richard Cornish
reply@reply.github.com
wrote:

**Comment by coleifer** [comment]
Forgot to mention -- not sure when you tried out micawber, but I added unit tests to the django integration not very long ago and discovered some places where stuff was being escaped and have fixed those.  So you might try pulling again, i think it may be fixed.
