### ISSUE TITLE
youtube &showinfo=0 not taken into account

### ISSUE THREAD

**Issue by sehmaschine** [worldcompany/djangoembed#4]
see http://help.youtube.com/group/youtube-howto/browse_thread/thread/3c342f54c33af012/2b8a08de12384900

if I´m using something like
http://www.youtube.com/watch?v=9bBkEQYdMM8&showinfo=0
the titles are still there.

not sure if that´s a djangoembed-issue though. 

thanks,
patrick

**Comment by coleifer** [comment]
i think that's a bit outside the scope of this project

**Comment by sehmaschine** [comment]
well, that´s your decision (of course) and I can happily accept this answer. nevertheless, you may wanna describe the "scope of this project" in order to clarify - because I personally thought it´s about embedding videos (and other stuff). when doing so, I (and others probably as well) need to add some variables (e.g. to hide the video-title).
btw (for anyone else struggeling with this issue): with something like http://github.com/embedly/embedly-jquery this can be achieved.

**Comment by coleifer** [comment]
i think i might've misunderstood - i thought this fell into the category of 'embed' and do something afterwards.  reopened.

**Comment by coleifer** [comment]
I'm going to close since youtube's oembed endpoint doesn't seem to recognize any difference between the url with the &showinfo=0 or without.

```
>>> import httplib2
>>> sock = httplib2.Http()
>>> vid = 'http://www.youtube.com/watch?v=9bBkEQYdMM8'
>>> showinfo = '&showinfo=0'
>>> endpoint = 'http://www.youtube.com/oembed?url='
>>> headers, normal = sock.request(endpoint + vid)
>>> headers, showinfo = sock.request(endpoint + vid + showinfo)
>>> normal
'{"provider_url": "http:\\/\\/www.youtube.com\\/", "title": "THE DO - ON MY     SHOULDERS \\/ OFFICIAL VIDEO", "html": "<object width=\\"480\\" height=\\"295\\"><param name=\\"movie\\" value=\\"http:\\/\\/www.youtube.com\\/v\\/9bBkEQYdMM8?fs=1\\"><\\/param><param name=\\"allowFullScreen\\" value=\\"true\\"><\\/param><param name=\\"allowscriptaccess\\" value=\\"always\\"><\\/param><embed src=\\"http:\\/\\/www.youtube.com\\/v\\/9bBkEQYdMM8?fs=1\\" type=\\"application\\/x-shockwave-flash\\" width=\\"480\\" height=\\"295\\" allowscriptaccess=\\"always\\" allowfullscreen=\\"true\\"><\\/embed><\\/object>", "author_name": "proddeluxe", "height": 295, "thumbnail_width": 480, "width": 480, "version": "1.0", "author_url": "http:\\/\\/www.youtube.com\\/user\\/proddeluxe", "provider_name": "YouTube", "thumbnail_url": "http:\\/\\/i2.ytimg.com\\/vi\\/9bBkEQYdMM8\\/hqdefault.jpg", "type": "video", "thumbnail_height": 360}'
>>> normal == showinfo
True
```
