### ISSUE TITLE
The New Twitter regex urls?

### ISSUE THREAD

**Issue by jasonmelgoza** [worldcompany/djangoembed#7]
I changed the regex and wild-card fields in the admin, successfully once before, but when I re-synced my project they were overwritten by the old stuff. Any clue on what the new urls would be?

I've tried these with no success:
regex: http://twitter.com/%23!/*/status/*
wild-card: http://twitter.com/#!/*/status/*

**Comment by coleifer** [comment]
embed.ly should be able to handle it

http://api.embed.ly/tools/generator

http://(twitter.com/._/status/._|twitter.com/._/statuses/._|mobile.twitter.com/._/status/._|mobile.twitter.com/._/statuses/._)

**Comment by jasonmelgoza** [comment]
**Awesome** tip! Here's the url that worked for me. 

```
http://twitter.com/.*/status/.*
```

Thanks!
